{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "redis.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels: {{ include "redis.selectorLabels" . | nindent 6 }}
  serviceName: {{ template "redis.name" . }}-resource-manager
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      labels: {{ include "redis.labels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: "{{ .Values.redis.image.pullPolicy }}"
        name: redis
        env:
        - name: REDIS_PASSWORD
          value: mypassword
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources: {{ toYaml .Values.redis.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /bitnami
          name: redis-data
     
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: redis-data
      {{- with .Values.redis.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end }}
