{{- if .Values.flyteadmin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-admin-config
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
data:
{{- with .Values.db.admin }}
  db.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.domain }}
  domain.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.logger }}
  logger.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.adminServer }}
  server.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.remoteData }}
  remoteData.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
  storage.yaml: | {{ tpl (include "storage" .) $ | nindent 4 }}
{{- with .Values.configmap.task_resource_defaults }}
  task_resource_defaults.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- if .Values.workflow_notifications.enabled }}
{{- with .Values.workflow_notifications.config }}
  notifications.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.external_events.enable }}
{{- with .Values.external_events }}
  external_events.yaml: |
    externalEvents: {{ tpl (toYaml .) $ | nindent 6 }}
{{- end }}
{{- end }}
{{- if .Values.cluster_resource_manager.enabled }}
{{- with .Values.cluster_resource_manager.config }}
  cluster_resources.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.workflow_scheduler.enabled }}
  {{- if eq .Values.workflow_scheduler.type "aws" }}
{{- with .Values.workflow_scheduler.config }}
  scheduler.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
  {{- end }}
{{- end }}
{{- end }}
