{{- if .Values.flyteadmin.enabled }}
---
{{- if .Values.flyteadmin.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flyteadmin.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
  {{- with .Values.flyteadmin.serviceAccount.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- with .Values.flyteadmin.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{ tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}

---
{{- if .Values.flyteadmin.serviceAccount.createClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "flyteadmin.name" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - flyte.lyft.com
  - rbac.authorization.k8s.io
  resources:
  - configmaps
  - flyteworkflows
  - namespaces
  - pods
  - resourcequotas
  - roles
  - rolebindings
  - secrets
  - services
  - serviceaccounts
  - spark-role
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "flyteadmin.name" . }}-binding
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "flyteadmin.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "flyteadmin.name" . }}
  namespace: {{ template "flyte.namespace" . }}
{{- end }}
{{- end }}
